# Generated by Django 4.2.7 on 2026-07-03 18:07

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default=patients.models.generate_unique_id, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=patients.models.generate_unique_id, max_length=10, unique=True),
        ),
    ]
