# Generated by Django 4.2.7 on 2026-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('depression', 'Depression'), ('anxiety', 'Anxiety'), ('sleep', 'Sleep'), ('appetite', 'Appetite'), ('energy', 'Energy'), ('mood', 'Mood'), ('social', 'Social Functioning'), ('general', 'General Health'), ('suicidality', 'Suicidality'), ('functioning', 'Functioning')], max_length=20),
        ),
    ]
