# Generated by Django 4.2.7 on 2026-07-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='full_report_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
